name: HCPokeBall
main: jp.harucraft.HCPokeBall
version: 2.0.0
api-version: 1.21.5
commands:
  hcpb:
    description:
    permission: hcpokeball.admin
    permission-message: You don't have <permission>