name: HCPokeBallReloaded
main: jp.haruserver.mc.hcpokeball.HCPokeBall
version: 1.0.2
api-version: 1.21.5
commands:
  hcpb:
    description:
    permission: hcpokeball.admin
    permission-message: You don't have <permission>